; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200


[env:esp32dev]
build_flags =
  -D PPG_FIRMWARE_VARIANT=0

[env:esp32dev_red_nir_12ch]
build_flags =
  -D PPG_FIRMWARE_VARIANT=12
  -D PPG_12CH_LED_DRIVE=0x06
  -D PPG_12CH_AGAIN=0x08

[env:esp32dev_red_nir_12ch_dim]
build_flags =
  -D PPG_FIRMWARE_VARIANT=12
  -D PPG_12CH_LED_DRIVE=0x04
  -D PPG_12CH_AGAIN=0x08

[env:esp32dev_red_nir_12ch_bright]
build_flags =
  -D PPG_FIRMWARE_VARIANT=12
  -D PPG_12CH_LED_DRIVE=0x10
  -D PPG_12CH_AGAIN=0x08

[env:esp32dev_18ch_lab]
build_flags =
  -D PPG_FIRMWARE_VARIANT=18
